### ISSUE TITLE
2FA not being recognized by HASS Integration 

### ISSUE THREAD

**Issue by TonyMontuna** [bretterer/home-assistant-rivian#157]
I have enabled 2 factor authentication on my rivian mobile app and assigned a key to a unique driver profile specifically for HASS. 

When I go to configure the remote settings, I get an error saying "Two-factor authentication is required to enable vehicle control" and it does not pair. 

However, I do have 2FA enabled on the app. 

I have restarted the integration, disabled and reenabled the integration, uninstalled the integration and reinstalled it, but nothing solves the issue.

**Comment by natekspencer** [comment]
2FA is profile specific. Have you tried logging into the website or app with that additional profile and enabled it there?

**Comment by TonyMontuna** [comment]
> All good, glad it was an easy fix!

quick question, while I have your attention, I can't figure out how to create buttons for the remote funtions, like lock and unlock for example. 

Is that done through the developer tools menu on the services tab? Is it a script I need to create? Any guidance would be greatly appreciated - I'm struggling a bit.

**Comment by natekspencer** [comment]
If you enable debug logging, you can potentially trace the connection attempt/issue a little better and post it here so we can help. What device do you run Home Assistant on? What is your BT scanner? Do you have other things using the BT radio already?

**Comment by TonyMontuna** [comment]
This is the error I'm seeing in the logs. I run HASS IO on a Dell Optiplex.
I use a Sena USB Bluetooth Adapter 300m Working Dist, UD100-G03 (300m
Working Dist. Exchangeable Antenna, Bluesoleil Driver (Works with Microsoft
Bluetooth Driver)), red, Black.

I do have other things using the BT radio like a thermometer/humidity
sensor in my bathroom

   -
   - Entity None (<class
   'custom_components.rivian.climate.RivianClimateEntity'>) implements
   HVACMode(s): off, heat_cool, heat and therefore implicitly supports the
   turn_on/turn_off methods without setting the proper ClimateEntityFeature.
   Please create a bug report at
   https://github.com/bretterer/home-assistant-rivian/issues

**Comment by natekspencer** [comment]
That error is unrelated (though should be fixed). If you enable debug logs, you should get a much more comprehensive log of the pairing process when you initiate it. It'll have outputs like:

```log
2024-05-28 10:02:55.918 DEBUG (MainThread) [custom_components.rivian.button] Searching for Rivian Phone Key
2024-05-28 10:02:55.921 ERROR (MainThread) [custom_components.rivian.button] Rivian Phone Key not found
2024-05-28 10:02:55.921 DEBUG (MainThread) [custom_components.rivian.button] Unable to complete pairing
```

**Comment by TonyMontuna** [comment]
[home-assistant_rivian_2024-05-28T16-06-07.496Z.log](https://github.com/bretterer/home-assistant-rivian/files/15472817/home-assistant_rivian_2024-05-28T16-06-07.496Z.log)

these are the complete logs

**Comment by natekspencer** [comment]
> I'm not sure what that error is so I'm not sure how to fix it, I thought it was related to the rivian app.

Sorry, that was more of a note for myself and the other integration devs that we should fix it.

It looks like your pairing process is almost finishing successfully:
```log
2024-05-28 11:50:08.485 DEBUG (MainThread) [custom_components.rivian.button] Searching for Rivian Phone Key
2024-05-28 11:50:08.485 DEBUG (MainThread) [custom_components.rivian.button] Found FC:A8:9B:EC:95:AB: Rivian Phone Key (RSSI: -70)
2024-05-28 11:50:08.486 DEBUG (MainThread) [custom_components.rivian.button] Making sure BT controller can be paired
2024-05-28 11:50:08.498 DEBUG (MainThread) [rivian.ble] Connecting to FC:A8:9B:EC:95:AB: Rivian Phone Key
2024-05-28 11:50:09.580 DEBUG (MainThread) [rivian.ble] Connected to FC:A8:9B:EC:95:AB: Rivian Phone Key
2024-05-28 11:50:09.807 DEBUG (MainThread) [rivian.ble] Validating id
2024-05-28 11:50:09.957 DEBUG (MainThread) [rivian.ble] Exchanging nonce
2024-05-28 11:50:10.258 DEBUG (MainThread) [rivian.ble] Attempting to pair
2024-05-28 11:50:11.206 DEBUG (MainThread) [rivian.ble] Couldn't connect to FC:A8:9B:EC:95:AB: Rivian Phone Key. Make sure you are in the correct vehicle and have selected "Set Up" for the appropriate key and try again: [org.bluez.Error.AuthenticationFailed] Authentication Failed
```

You may just need to try a few more times. It can be finicky. It also may be helpful to temporarily disable any of the other devices/integrations that are using the BT adapter since each BT adapter has limited slots available and could be consumed by these.

**Comment by TonyMontuna** [comment]
Gotcha. I appreciate your help with this. I’m seeing a nonstop logging of
Bluetooth MAC address changes in my log book so perhaps that has something
to do with it. I’m doing some troubleshooting now but I’ll keep you posted
if I find any success.

**Comment by TonyMontuna** [comment]
I've been trying again to get the truck paired but I'm still not able to get it to pair via bluetooth. It's odd cause it looks like it will work but doesn't. Do you have perhaps another way of pairing it or a workaround to get it paired of sorts? I thought for a second to download the old HASS version where it's not required and then updating to the current version but thought that wouldn't work. Looking forward to hearing your take but I've attached the latest debug logs for you to get a better idea.
[home-assistant_rivian_2024-05-29T02-31-45.707Z.log](https://github.com/bretterer/home-assistant-rivian/files/15478024/home-assistant_rivian_2024-05-29T02-31-45.707Z.log)

**Comment by natekspencer** [comment]
> I thought for a second to download the old HASS version where it's not required

The requirement was added on Rivian's end, so it will not work unless bluetooth pairing is completed.

> Sena USB Bluetooth Adapter 300m Working Dist, UD100-G03 (300m Working Dist. Exchangeable Antenna, Bluesoleil Driver (Works with Microsoft Bluetooth Driver)), red, Black

In looking this up on Amazon, it appears it only supports Bluetooth 4.0. I have a more limited understanding of the Bluetooth spec, but I believe 4.2 is required to support LESec connections: https://stackoverflow.com/questions/36260101/bluez-le-secure-pairing-using-elliptical-curve-diffie-hellman-from-command-line

I looks like you'll need a different adapter or an ESP32 running [bluetooth proxy](https://esphome.io/projects/?type=bluetooth). I should have noticed this with the `Authentication Failed` error, but it's been a while since I worked on it and @doggkruse is the true expert.

**Comment by TonyMontuna** [comment]
I purchased a different bluetooth adapter that supports 4.2, however, the issue persists. 
[home-assistant_rivian_2024-05-29T14-37-25.668Z.log](https://github.com/bretterer/home-assistant-rivian/files/15486000/home-assistant_rivian_2024-05-29T14-37-25.668Z.log)


This is the adapter I'm using now: [Long Range USB Bluetooth 5.3 Adapter for Desktop PC - 328FT Wireless Transfer for Mouse, Keyboard, Headphones - Win11/10/8.1 Support](https://www.amazon.com/dp/B0C1ZDYFSZ?ref=ppx_yo2ov_dt_b_product_details&th=1)

Any other suggestions I could try?

**Comment by natekspencer** [comment]
I would suggest the ESP32 with bluetooth proxy route in that case. I know a lot of people have had success with that when other adapters have failed.

**Comment by TonyMontuna** [comment]
I don't really think range is the problem cause it seems to be finding the truck but I'm happy to give it a shot. 

[Would this process be what you have in mind? ](https://www.youtube.com/watch?v=VfRwtlITUFs)

If so, [I'll purchase that now and hopefully I can get a same day delivery of this](https://www.amazon.com/HiLetgo-ESP-WROOM-32-Development-Microcontroller-Integrated/dp/B0718T232Z?crid=1QCWNHZTZ90U&keywords=esp32&qid=1684737966&sprefix=esp32,aps,314&sr=8-5&linkCode=sl1&tag=simplysmar0f1-20&linkId=0711fb51c8762461f3b85b1fe3b4abdf&language=en_US&ref_=as_li_ss_tl)

**Comment by TonyMontuna** [comment]
Just wanted to close the loop here for anyone who may check this in the future. 

Using the ESP32 device worked fairly quickly. 

I did get a 30 foot usb extension cable but it still did not get a strong enough signal, however, the ESP32 device (easy setup for a non tech career person) worked quickly. I now have remote access. 

Thank you for all your help in this thread!
